version: '3'

services:
  php-app:
    build:
      context: .
      dockerfile: dockerfile-php
    ports:
      - "8080:80" # Map host port 8080 to container port 80
    depends_on:
      - mysql-db

  mysql-db:
    build:
      context: .
      dockerfile: dockerfile-mysql
    ports:
      - "3306:3306" # Map host port 3306 to container port 3306